#!/usr/bin/env ansible-playbook
---
- hosts: all

  pre_tasks:
    - name: Check Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.9', '>=')
        msg: The Ansible version is too old for this playbook

  tasks:
    - name: Execute apt update if the last one is more than 1 hour ago
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Ensure the gpg package is installed
      become: yes
      package:
        name: gpg

    - name: Include the alvistack.podman role
      include_role: { name: alvistack.podman }
      vars:
        ansible_become: yes
